# Generated by Django 5.2.1 on 2025-06-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_description_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "permissions": [
                    ("can_edit_category", "Может редактировать категории"),
                    ("can_delete_category", "Может удалять категории"),
                    ("can_add_category", "Может добавлять категории"),
                ],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "price"],
                "permissions": [
                    ("can_edit_product", "Может редактировать товары"),
                    ("can_delete_product", "Может удалять товары"),
                    ("can_add_product", "Может добавлять товары"),
                    ("can_view_product", "Может просматривать товары"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
