# Generated by Django 5.2.1 on 2025-06-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_category_options_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "price"],
                "permissions": [
                    ("can_unpublish_product", "Может снимать продукт с публикации"),
                    ("can_delete_product", "Может удалять продукты"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
